import AllStudents, { StudentDataContext } from "@/Context/AllStudents";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AllStudents>
        <body>{children}</body>
      </AllStudents>
    </html>
  );
}
